include:
  - ./proxy.yaml
services:
  web:
    container_name: mia-site
    image: cr.yandex/${REGISTRY_ID}/mia-site:1.3
    expose:
      - 8080
    volumes:
      - /home/user/logs:/app/logs
    ports:
      - 8080:8080
    restart: on-failure
